version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 65952
      MONGO_INITDB_DATABASE: app
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  stake-backend:
    image: dfygs8dufghsdf/fgsd9f6ws7f96s-saub
    restart: always
    env_file:
      - .env
    ports:
      - "80:3000"